### ISSUE TITLE
Cannot set Windows wallpaper

### ISSUE THREAD

**Issue by toowhite** [sindresorhus/windows-wallpaper#12]
Hi I am developing a tool where I tried to use your program. But in some case I cannot set wallpaper use the following command:
`wallpaper set [Filepath] --scale tile`

This is the file I used
[_tmp_new.zip](https://github.com/sindresorhus/win-wallpaper/files/11573241/_tmp_new.zip)

And in some other moment I did see it works, after that I kept trying but always failed. 

Hope you can help me. I really like the simplicity and user-friendliness of this tool and would like to incorporate it into my work. Thank you!

**Comment by sindresorhus** [comment]
Probably related to the issue mentioned in https://github.com/sindresorhus/wallpaper/pull/87

**Comment by sindresorhus** [comment]
Please try: https://github.com/sindresorhus/win-wallpaper/releases/tag/v3.0.2
